# Separate deployment of the broken-server, if needed for testing
# Not deployed by default

# Deploy with:

# kubectl apply -f config/samples/mcpserverregistration-broken-server.yaml
# kubectl apply -f config/test-servers/broken-server-deployment.yaml
# kubectl apply -f config/test-servers/broken-server-service.yaml
# kubectl apply -f config/test-servers/broken-server-httproute.yaml
# kubectl apply -f config/test-servers/broken-server-httproute-ext.yaml

apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPServerRegistration
metadata:
  name: test-broken-server
  namespace: mcp-test
  labels:
    mcp.kuadrant.io/managed: "true"
spec:
  prefix: broke_
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mcp-broken-server-route
