---
apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPServerRegistration
metadata:
  name: conformance-server
  namespace: mcp-test
  labels:
    mcp.kuadrant.io/managed: 'true'
spec:
  # prefix: conformance_ # conformance test suite expects no prefix
  targetRef:
    # MCP Conformance Server - TypeScript SDK based conformance test server
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: conformance-server-route
